# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwissPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=38)),
                ('place_type', models.CharField(max_length=50)),
                ('altitude', models.FloatField()),
                ('name_uuid', models.CharField(max_length=38)),
                ('name', models.CharField(max_length=250)),
                ('lang_code', models.CharField(max_length=50)),
                ('name_type', models.CharField(max_length=20)),
                ('name_group', models.CharField(max_length=38)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=21781)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('totalup', models.IntegerField(verbose_name='Total elevation difference up')),
                ('totaldown', models.IntegerField(verbose_name='Total elevation difference down')),
                ('length', models.FloatField(verbose_name='Total length of the track in m')),
                ('line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
