# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swissplaces',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=21781),
        ),
    ]
