# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20160614_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='line',
            new_name='geom',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='name',
        ),
        migrations.AddField(
            model_name='tracks',
            name='swissmobility_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
