# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 15:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20160615_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracks',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326, verbose_name='line geometry'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='length',
            field=models.FloatField(default=0, verbose_name='Total length of the track in m'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='totaldown',
            field=models.IntegerField(default=0, verbose_name='Total elevation difference down'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='totalup',
            field=models.IntegerField(default=0, verbose_name='Total elevation difference up'),
        ),
    ]
