# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20160615_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=21781, verbose_name='line geometry'),
        ),
    ]
