# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_auto_20160616_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='totaldown',
            field=models.FloatField(default=0, verbose_name='Total elevation difference down'),
        ),
        migrations.AlterField(
            model_name='track',
            name='totalup',
            field=models.FloatField(default=0, verbose_name='Total elevation difference up'),
        ),
    ]
