# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default='', verbose_name='Text description of the Place'),
        ),
    ]
