# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20160622_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 22, 8, 56, 22, 693103, tzinfo=utc), verbose_name='Time of last creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 22, 8, 56, 30, 237228, tzinfo=utc), verbose_name='Time of last update'),
            preserve_default=False,
        ),
    ]
