# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_add_choices_to_place_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='switzerland_mobility_cookie',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(
                choices=[
                    ('PLA', 'Place'),
                    ('Constructions', (
                        ('BDG', 'Single Building'),
                        ('OBG', 'Open Building'),
                        ('TWR', 'Tower'),
                        ('SBG', 'Sacred Building'),
                        ('CPL', 'Chapel'),
                        ('SHR', 'Wayside Shrine'),
                        ('MNT', 'Monument'),
                        ('FTN', 'Fountain'))),
                    ('Features', (
                        ('SUM', 'Summit'),
                        ('HIL', 'Hill'),
                        ('PAS', 'Pass'),
                        ('BEL', 'Belay'),
                        ('WTF', 'Waterfall'),
                        ('CAV', 'Cave'),
                        ('SRC', 'Source'),
                        ('BLD', 'Boulder'),
                        ('POV', 'Point of View'))),
                    ('Public Transport', (
                        ('BUS', 'Bus Station'),
                        ('TRA', 'Train Station'),
                        ('OTH', 'Other Station'),
                        ('BOA', 'Boat Station'))),
                    ('Roads', (
                        ('EXT', 'Exit'),
                        ('EAE', 'Entry and Exit'),
                        ('RPS', 'Road Pass'),
                        ('ICG', 'Interchange'),
                        ('LST', 'Loading Station'),
                        ('PKG', 'Parking'))),
                    ('Customs', (
                        ('C24', 'Customhouse 24h'),
                        ('C24LT', 'Customhouse 24h limited'),
                        ('CLT', 'Customhouse limited'),
                        ('LMK', 'Landmark'))),
                    ('Personal', (
                        ('HOM', 'Home'),
                        ('WRK', 'Work'),
                        ('GYM', 'Gym'),
                        ('HOL', 'Holiday Place'),
                        ('FRD', "Friend's place"),
                        ('CST', 'Other place')))
                ], max_length=26
            ),
        ),
    ]
