# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 20:24
from __future__ import unicode_literals

import homebytwo.routes.models.track
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20170315_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homebytwo.routes.models.track.get_image_path),
        ),
    ]
