# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:45
from __future__ import unicode_literals

import homebytwo.routes.models.track
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_route_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=homebytwo.routes.models.track.get_image_path),
        ),
    ]
