# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_initial_activity_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='routes.ActivityType'),
        ),
    ]
