# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_route_activity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperformance',
            old_name='flat_pace',
            new_name='flat_speed',
        ),
        migrations.RenameField(
            model_name='activitytype',
            old_name='default_flat_pace',
            new_name='default_flat_speed',
        ),
    ]
