# Generated by Django 2.0.4 on 2018-05-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_auto_20170630_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of last update'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_place',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ends_route',
                to='routes.Place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_place',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='starts_route',
                to='routes.Place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Time of creation'),
        ),
    ]
