# Generated by Django 2.0.4 on 2018-05-03 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0014_auto_20180503_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='place',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of last update'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of creation'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('owner', 'data_source', 'source_id')},
        ),
    ]
