# Generated by Django 2.0.5 on 2018-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_auto_20180503_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('PLA', 'Place'), ('LPL', 'Local Place'), ('Constructions', (('BDG', 'Single Building'), ('OBG', 'Open Building'), ('TWR', 'Tower'), ('SBG', 'Sacred Building'), ('CPL', 'Chapel'), ('SHR', 'Wayside Shrine'), ('MNT', 'Monument'), ('FTN', 'Fountain'))), ('Features', (('SUM', 'Summit'), ('HIL', 'Hill'), ('PAS', 'Pass'), ('BEL', 'Belay'), ('WTF', 'Waterfall'), ('CAV', 'Cave'), ('SRC', 'Source'), ('BLD', 'Boulder'), ('POV', 'Point of View'))), ('Public Transport', (('BUS', 'Bus Station'), ('TRA', 'Train Station'), ('OTH', 'Other Station'), ('BOA', 'Boat Station'))), ('Roads', (('EXT', 'Exit'), ('EAE', 'Entry and Exit'), ('RPS', 'Road Pass'), ('ICG', 'Interchange'), ('LST', 'Loading Station'), ('PKG', 'Parking'))), ('Customs', (('C24', 'Customhouse 24h'), ('C24LT', 'Customhouse 24h limited'), ('CLT', 'Customhouse limited'), ('LMK', 'Landmark'))), ('Personal', (('HOM', 'Home'), ('WRK', 'Work'), ('GYM', 'Gym'), ('HOL', 'Holiday Place'), ('FRD', "Friend's place"), ('CST', 'Other place')))], max_length=26),
        ),
    ]
