# Generated by Django 2.1.5 on 2019-10-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_auto_20180831_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='strava_token',
            new_name='strava_access_token',
        ),
        migrations.AddField(
            model_name='athlete',
            name='strava_refresh_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='strava_token_expires_at',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
