# Generated by Django 2.1.5 on 2019-01-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_auto_20190125_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='altitude_on_route',
        ),
    ]
