# Generated by Django 2.1.5 on 2019-11-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_auto_20191018_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='strava_access_token',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='strava_refresh_token',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='strava_token_expires_at',
        ),
    ]
