# Generated by Django 2.1.11 on 2019-11-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0018_auto_20191101_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strava_id', models.BigIntegerField(unique=True)),
                ('workout_type', models.SmallIntegerField(blank=True, choices=[(None, 'None'), ('0', 'default run'), ('1', 'race run'), ('2', 'long run'), ('3', 'workout run'), ('10', 'default ride'), ('11', 'race ride'), ('12', 'workout ride')], null=True)),
                ('start_date', models.DateTimeField()),
                ('manual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='activityperformance',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routes.ActivityType'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(choices=[('AlpineSki', 'Alpine Ski'), ('BackcountrySki', 'Backcountry Ski'), ('Canoeing', 'Canoeing'), ('Crossfit', 'Crossfit'), ('EBikeRide', 'E-Bike Ride'), ('Elliptical', 'Elliptical'), ('Golf', 'Golf'), ('Handcycle', 'Handcycle'), ('Hike', 'Hike'), ('IceSkate', 'Ice Skate'), ('InlineSkate', 'Inline Skate'), ('Kayaking', 'Kayaking'), ('Kitesurf', 'Kitesurf'), ('NordicSki', 'Nordic Ski'), ('Ride', 'Ride'), ('RockClimbing', 'Rock Climbing'), ('RollerSki', 'Roller Ski'), ('Rowing', 'Rowing'), ('Run', 'Run'), ('Sail', 'Sail'), ('Skateboard', 'Skateboard'), ('Snowboard', 'Snowboard'), ('Snowshoe', 'Snowshoe'), ('Soccer', 'Soccer'), ('StairStepper', 'Stair Stepper'), ('StandUpPaddling', 'Stand-Up Paddling'), ('Surfing', 'Surfing'), ('Swim', 'Swim'), ('Velomobile', 'Velomobile'), ('VirtualRide', 'Virtual Ride'), ('VirtualRun', 'Virtual Run'), ('Walk', 'Walk'), ('WeightTraining', 'Weight Training'), ('Wheelchair', 'Wheelchair'), ('Windsurf', 'Windsurf'), ('Workout', 'Workout'), ('Yoga', 'Yoga')], max_length=24),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routes.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Athlete'),
        ),
        migrations.AddField(
            model_name='activity',
            name='gear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.Gear'),
        ),
    ]
