# Generated by Django 2.1.11 on 2019-11-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0019_auto_20191105_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='strava_id',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
