# Generated by Django 2.1.11 on 2019-11-06 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0021_gear_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of last update'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Activity distance in m'),
        ),
        migrations.AddField(
            model_name='activity',
            name='elapsed_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Total activity time as timedelta'),
        ),
        migrations.AddField(
            model_name='activity',
            name='moving_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Movement time as timedelta'),
        ),
        migrations.AddField(
            model_name='activity',
            name='totalup',
            field=models.FloatField(blank=True, null=True, verbose_name='Total elevation gain in m'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of creation'),
        ),
    ]
