# Generated by Django 2.1.11 on 2019-11-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0022_auto_20191106_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='activies',
            new_name='activity_type',
        ),
    ]
