# Generated by Django 2.1.11 on 2019-11-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0023_auto_20191107_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(choices=[('AlpineSki', 'Alpine Ski'), ('BackcountrySki', 'Backcountry Ski'), ('Canoeing', 'Canoeing'), ('Crossfit', 'Crossfit'), ('EBikeRide', 'E-Bike Ride'), ('Elliptical', 'Elliptical'), ('Golf', 'Golf'), ('Handcycle', 'Handcycle'), ('Hike', 'Hike'), ('IceSkate', 'Ice Skate'), ('InlineSkate', 'Inline Skate'), ('Kayaking', 'Kayaking'), ('Kitesurf', 'Kitesurf'), ('NordicSki', 'Nordic Ski'), ('Ride', 'Ride'), ('RockClimbing', 'Rock Climbing'), ('RollerSki', 'Roller Ski'), ('Rowing', 'Rowing'), ('Run', 'Run'), ('Sail', 'Sail'), ('Skateboard', 'Skateboard'), ('Snowboard', 'Snowboard'), ('Snowshoe', 'Snowshoe'), ('Soccer', 'Soccer'), ('StairStepper', 'Stair Stepper'), ('StandUpPaddling', 'Stand-Up Paddling'), ('Surfing', 'Surfing'), ('Swim', 'Swim'), ('Velomobile', 'Velomobile'), ('VirtualRide', 'Virtual Ride'), ('VirtualRun', 'Virtual Run'), ('Walk', 'Walk'), ('WeightTraining', 'Weight Training'), ('Wheelchair', 'Wheelchair'), ('Windsurf', 'Windsurf'), ('Workout', 'Workout'), ('Yoga', 'Yoga')], max_length=24, unique=True),
        ),
    ]
