# Generated by Django 2.1.11 on 2019-11-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0024_auto_20191107_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.SmallIntegerField(blank=True, choices=[(None, 'None'), (0, 'default run'), (1, 'race run'), (2, 'long run'), (3, 'workout run'), (10, 'default ride'), (11, 'race ride'), (12, 'workout ride')], null=True),
        ),
    ]
