# Generated by Django 2.1.11 on 2019-11-12 12:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0025_auto_20191107_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time of last update')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Time of creation')),
                ('date_generated', models.DateTimeField()),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('request_meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.PositiveIntegerField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='routes.ActivityType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='routes.Athlete'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='gear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='routes.Gear'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gears', to='routes.Athlete'),
        ),
    ]
