# Generated by Django 2.1.11 on 2019-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0026_auto_20191112_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='webhooktransaction',
            options={'ordering': ['-date_generated']},
        ),
        migrations.AlterField(
            model_name='webhooktransaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error'), (4, 'Skipped')], default=1),
        ),
    ]
