# Generated by Django 2.1.11 on 2019-11-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0026_auto_20191112_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'activities'},
        ),
    ]
