# Generated by Django 2.1 on 2019-11-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0027_auto_20191115_1351'),
        ('routes', '0027_auto_20191118_1210'),
    ]

    operations = [
    ]
