# Generated by Django 2.1.11 on 2019-11-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0029_auto_20191119_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='owner',
        ),
        migrations.AlterField(
            model_name='route',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='routes.Athlete'),
        ),
    ]
