# Generated by Django 2.1.11 on 2019-11-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0030_auto_20191119_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutePlace',
            new_name='Checkpoint',
        ),
    ]
