# Generated by Django 2.1.11 on 2019-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0031_auto_20191120_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='altitude_on_route',
        ),
        migrations.AlterField(
            model_name='place',
            name='data_source',
            field=models.CharField(default='homebytwo', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='place',
            name='source_id',
            field=models.CharField(max_length=50, verbose_name='ID at the data source'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
