# Generated by Django 2.2 on 2019-11-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0032_auto_20191120_2020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together={('route', 'place', 'line_location')},
        ),
    ]
