# Generated by Django 2.2.8 on 2019-12-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0033_auto_20191126_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='garmin_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
