# Generated by Django 2.2.8 on 2019-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0035_drop_lat_lng_columns_in_data_20191212_0742'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.UniqueConstraint(fields=('route', 'place', 'line_location'), name='unique checkpoint on route'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('data_source', 'source_id'), name='unique place for source'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('athlete', 'data_source', 'source_id'), name='unique route for athlete'),
        ),
    ]
