# Generated by Django 2.2.8 on 2019-12-20 20:16

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Route = apps.get_model('routes', 'Route')
    for route in Route.objects.all():
        route.uuid = uuid.uuid4()
        route.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0037_add_nullable_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
