# Generated by Django 2.2.8 on 2019-12-20 20:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0038_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(unique=True, default=uuid.uuid4, editable=False, serialize=False),
        ),
    ]
