# Generated by Django 2.2.8 on 2020-01-01 16:37

from django.db import migrations, models
import homebytwo.routes.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0039_make_uuid_field_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='data',
            field=homebytwo.routes.fields.DataFrameField(null=True, unique_fields=['uuid']),
        ),
        migrations.AlterField(
            model_name='route',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
