# Generated by Django 2.2.8 on 2020-01-02 02:39

from django.db import migrations
import homebytwo.routes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0040_auto_20200101_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='streams',
            field=homebytwo.routes.fields.DataFrameField(null=True, unique_fields=['strava_id'], upload_to='streams'),
        ),
    ]
