# Generated by Django 2.2.13 on 2020-07-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0042_activity_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='length',
            new_name='total_distance',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='totalup',
            new_name='total_elevation_gain',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='totaldown',
            new_name='total_elevation_loss',
        ),
    ]
