# Generated by Django 2.2.13 on 2020-07-05 07:11

from django.db import migrations


def rename_length_column_in_distance(apps, schema_editor):
    Route = apps.get_model("routes", "Route")
    for route in Route.objects.all():
        if "distance" not in route.data.columns:
            try:
                route.data.rename(columns={"length": "distance"}, inplace=True)
            except KeyError:
                continue
            route.save(update_fields=["data"])


def rename_distance_column_in_length(apps, schema_editor):
    Route = apps.get_model("routes", "Route")
    for route in Route.objects.all():
        if "length" not in route.data.columns:
            try:
                route.data.rename(columns={"distance": "length"}, inplace=True)
            except KeyError:
                continue
            route.save(update_fields=["data"])


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0043_rename_route_attributes"),
    ]

    operations = [
        migrations.RunPython(
            rename_length_column_in_distance, rename_distance_column_in_length
        )
    ]
