# Generated by Django 2.2.13 on 2020-07-07 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0044_rename_data_distance_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperformance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of last update'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityperformance',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of creation'),
        ),
    ]
