# Generated by Django 2.2.16 on 2020-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0046_change_upload_to_in_track_and_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='manual',
        ),
        migrations.AddField(
            model_name='activity',
            name='skip_streams_import',
            field=models.BooleanField(default=False),
        ),
    ]
