# Generated by Django 2.2.16 on 2020-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0046_change_upload_to_in_track_and_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='source_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
