# Generated by Django 2.2.16 on 2020-10-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0047_source_id_nullable'),
        ('routes', '0048_athlete_activities_imported'),
    ]

    operations = [
    ]
