# Generated by Django 2.2.16 on 2020-10-20 10:15

from django.db import migrations
from django.core.management import call_command


def fix_routes_data(apps, schema_editor):
    call_command('fix_routes_data', verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0049_merge_20201002_1037'),
    ]

    operations = [
        migrations.RunPython(fix_routes_data),
    ]
