# Generated by Django 2.2.16 on 2020-10-26 20:55

from django.db import migrations


def delete_non_geonames_places(apps, schema_editor):
    print("deleting non-geonames places... ")
    Place = apps.get_model("routes", "Place")
    Place.objects.exclude(data_source="geonames").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0050_create_place_type_model"),
    ]

    operations = [migrations.RunPython(delete_non_geonames_places)]
