# Generated by Django 2.2.16 on 2020-10-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0051_delete_non_geonames_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='old_place_type',
        ),
        migrations.RemoveField(
            model_name='place',
            name='public_transport',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(on_delete='CASCADE', to='routes.PlaceType'),
        ),
    ]
