# Generated by Django 2.2.17 on 2020-11-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0051_create_place_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='CH', max_length=2),
        ),
    ]
