# Generated by Django 2.2.17 on 2020-11-05 11:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models

from homebytwo.importers.coutries import import_country_geometries


def import_countries(apps, schema_editor):
    import_country_geometries()


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0051_create_place_type_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "iso3",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("iso2", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=250)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete="SET_NULL",
                related_name="places",
                to="routes.Country",
            ),
        ),
        migrations.RunPython(import_countries, migrations.RunPython.noop),
    ]
