# Generated by Django 2.2.17 on 2020-11-05 15:36
import django.contrib.gis.db.models.fields
from django.db import migrations, router
from tqdm import tqdm


class RunUpdateSRID(migrations.RunPython):
    """
    Monkey patch migrations.RunPython for the sake of DRY.
    This operation is not reversible.
    """
    def __init__(self, *args, **kwargs):
        self.model = kwargs.pop("model")
        self.new_srid = kwargs.pop("new_srid")
        code = migrate_geom_to_new_srid
        super().__init__(code, *args, **kwargs)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        from_state.clear_delayed_apps_cache()
        if router.allow_migrate(
            schema_editor.connection.alias, app_label, **self.hints
        ):
            self.code(
                from_state.apps,
                schema_editor,
                self.model,
                self.new_srid,
            )


def migrate_geom_to_new_srid(apps, schema_editor, model, new_srid):
    print(f"migrating {model} to srid: {new_srid}...")

    Model = apps.get_model("routes", model)
    for instance in tqdm(
        Model.objects.all(),
        total=Model.objects.count(),
        unit=model + "s",
        unit_scale=True,
    ):
        instance.geom = instance.old_geom.transform(new_srid, clone=True)
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0052_place_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="geom",
            new_name="old_geom",
        ),
        migrations.AddField(
            model_name="route",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                null=True, srid=3857
            ),
        ),
        migrations.RenameField(
            model_name="place",
            old_name="geom",
            new_name="old_geom",
        ),
        migrations.AddField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=3857),
        ),
        RunUpdateSRID(
            model="route",
            new_srid=3857,
        ),
        RunUpdateSRID(
            model="place",
            new_srid=3857,
        ),
        migrations.RemoveField(
            model_name="route",
            name="old_geom",
        ),
        migrations.RemoveField(
            model_name="place",
            name="old_geom",
        ),
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
        migrations.AlterField(
            model_name="route",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                srid=3857, verbose_name="line geometry"
            ),
        ),
    ]
