# Generated by Django 2.2.17 on 2020-11-05 15:36
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0052_place_country"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE routes_place
            ALTER COLUMN geom TYPE geometry(POINT, 3857)
            USING ST_Transform(ST_SetSRID(geom, 21781), 3857);
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE routes_route
            ALTER COLUMN geom TYPE geometry(LINESTRING, 3857)
            USING ST_Transform(ST_SetSRID(geom, 21781), 3857);
            """
        ),
        migrations.AlterField(
            model_name="route",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
