# Generated by Django 2.2.16 on 2020-10-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0052_remove_old_place_type_field'),
        ('routes', '0050_fix_route_data'),
    ]

    operations = [
    ]
