# Generated by Django 2.2.17 on 2020-11-05 15:36
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0052_place_country"),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT UpdateGeometrySRID('routes_place','geom',3857);",
        ),
        migrations.RunSQL(
            "SELECT UpdateGeometrySRID('routes_route','geom',3857);",
        ),
        migrations.AlterField(
            model_name="route",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(srid=3857),
        ),
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
