# Generated by Django 2.2.17 on 2020-11-09 10:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0053_migrate_to_3857_srid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=3857, verbose_name='line geometry'),
        ),
    ]
