# Generated by Django 2.2.17 on 2020-11-17 20:44

from django.db import migrations, models
import django.db.models.deletion
import homebytwo.routes.fields
import homebytwo.routes.models.activity


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0054_fix_django_doctor_field_issues_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='activity_type',
        ),
    ]
