# Generated by Django 2.2.17 on 2020-11-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0054_fix_django_doctor_field_issues_'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='use_for_training',
            field=models.BooleanField(default=True),
        ),
    ]
