# Generated by Django 2.2.17 on 2020-11-17 20:44

from django.db import migrations, models
import django.db.models.deletion
import homebytwo.routes.fields
import homebytwo.routes.models.activity


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0055_remove_athlete_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperformance',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performances', to='routes.ActivityType'),
        ),
        migrations.AlterField(
            model_name='activityperformance',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='routes.Athlete'),
        ),
    ]
