# Generated by Django 2.2.17 on 2020-12-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0058_adapt_max_min_pace_for_activity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='min_pace',
            field=models.FloatField(default=0.1),
        ),
    ]
