sudo: false
language: python
python:
  - "3.5"
cache: pip
services:
  - postgresql

dist: trusty

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

install:
  - pip install tox-travis

env:
  - TOXENV=py35, DATABASE_URL=postgis://postgres@localhost/travisdb

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres

script:
  - tox
