os: linux
dist: bionic

language: python
python:
  - "3.7"

cache: pip

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11-postgis-2.5

install:
  - pip install tox-travis

env:
  - TOXENV=py37, DATABASE_URL=postgis://postgres@localhost/travisdb

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres
  - psql -c "CREATE EXTENSION postgis_topology;" -U postgres

script:
  - tox
