# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20170315_2056'),
        ('importers', '0002_auto_20170315_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravaroute',
            name='route_ptr',
        ),
        migrations.DeleteModel(
            name='StravaRoute',
        ),
        migrations.CreateModel(
            name='StravaRoute',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('routes.route',),
        ),
    ]
