# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 06:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('altitude', models.FloatField()),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='', verbose_name='Text description of the Place')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time of last creation')),
                ('lang', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=21781)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', verbose_name='Text description of the Route')),
                ('totalup', models.FloatField(default=0, verbose_name='Total elevation gain in m')),
                ('totaldown', models.FloatField(default=0, verbose_name='Total elevation loss in m')),
                ('length', models.FloatField(default=0, verbose_name='Total length of the track in m')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=21781, verbose_name='line geometry')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=21781, verbose_name='line geometry')),
                ('end_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ends', to='routes.Place')),
                ('start_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starts', to='routes.Place')),
            ],
        ),
    ]
