# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(default='', verbose_name='Text description of the Route'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='totaldown',
            field=models.FloatField(default=0, verbose_name='Total elevation difference down in mq'),
        ),
        migrations.AlterField(
            model_name='route',
            name='totalup',
            field=models.FloatField(default=0, verbose_name='Total elevation difference up in m'),
        ),
    ]
