# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 20:54
from __future__ import unicode_literals

from django.db import migrations
import routes.models.track


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='data',
            field=routes.models.track.DataFrameField(max_length=100, null=True),
        ),
    ]
