# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vam_up', models.FloatField(default=400)),
                ('vam_down', models.FloatField(default=2000)),
                ('flat_pace', models.FloatField(default=4000)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='lang',
        ),
        migrations.AddField(
            model_name='activityperformance',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.ActivityType'),
        ),
        migrations.AddField(
            model_name='activityperformance',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Athlete'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='activies',
            field=models.ManyToManyField(through='routes.ActivityPerformance', to='routes.ActivityType'),
        ),
    ]
