# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20160622_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(default='', verbose_name='Text description of the Route'),
        ),
    ]
