# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20170125_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(default='', verbose_name='Textual description'),
        ),
    ]
