# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20170125_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='start_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routes.Place'),
            preserve_default=False,
        ),
    ]
