# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20160622_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 22, 8, 56, 33, 653180, tzinfo=utc), verbose_name='Time of last creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 22, 8, 56, 35, 493387, tzinfo=utc), verbose_name='Time of last update'),
            preserve_default=False,
        ),
    ]
