# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20160702_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='description',
            field=models.TextField(default=b''),
        ),
    ]
