# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20160622_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='Created',
            new_name='created',
        ),
    ]
