# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_route_start_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ends_route', to='routes.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='start_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts_route', to='routes.Place'),
        ),
    ]
