# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 13:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20160622_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(max_length=50)),
                ('altitude', models.FloatField()),
                ('name', models.CharField(max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=21781)),
                ('description', models.TextField(default='', verbose_name='Text description of the Place')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time of last creation')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=21781, verbose_name='line geometry')),
                ('end_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ends', to='routes.Place')),
                ('start_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starts', to='routes.Place')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='totaldown',
            field=models.FloatField(default=0, verbose_name='Total elevation difference down in m'),
        ),
    ]
