# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20170131_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ends_route', to='routes.Place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starts_route', to='routes.Place'),
        ),
    ]
