# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20170131_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='data',
            field=models.FileField(blank=True, upload_to='track_data/'),
        ),
    ]
