# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_route_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='strava_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
