# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 20:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20160623_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
