# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_route_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_location', models.FloatField(default=0)),
                ('altitude_on_route', models.FloatField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='places',
            field=models.ManyToManyField(blank=True, through='routes.PlaceRoute', to='routes.Place'),
        ),
    ]
