# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20160703_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='switzerland_mobility_cookie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
