# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_auto_20160625_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='language',
            new_name='lang',
        ),
    ]
