# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_auto_20160703_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='public_transport',
            field=models.BooleanField(default=False),
        ),
    ]
