# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_place_public_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='elevation_down',
            field=models.FloatField(default=0, verbose_name='elevation loss in m'),
        ),
        migrations.AddField(
            model_name='segment',
            name='elevation_up',
            field=models.FloatField(default=0, verbose_name='elevation gain in m'),
        ),
    ]
