# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 07:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_auto_20160625_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='route',
            name='swissmobility_id',
        ),
        migrations.AlterField(
            model_name='place',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=21781),
        ),
    ]
