# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20160629_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='owner',
            field=models.BigIntegerField(default=0, verbose_name='Switzerland Mobility User ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='route',
            name='totaldown',
            field=models.FloatField(default=0, verbose_name='Total elevation loss in m'),
        ),
        migrations.AlterField(
            model_name='route',
            name='totalup',
            field=models.FloatField(default=0, verbose_name='Total elevation gain in m'),
        ),
    ]
