# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20161128_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='place',
            name='created',
        ),
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of creation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name of the place'),
        ),
    ]
