# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20161214_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='type',
            new_name='place_type',
        ),
        migrations.AddField(
            model_name='place',
            name='data_source',
            field=models.CharField(default='swissname3d', max_length=50, verbose_name='Where the place came from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='source_id',
            field=models.CharField(default=1, max_length=50, verbose_name='Unique id at the data source'),
            preserve_default=False,
        ),
    ]
