# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_auto_20161214_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='source_id',
            field=models.UUIDField(verbose_name='UUID at the data source'),
        ),
    ]
