# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_auto_20161215_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='data_source',
        ),
    ]
