# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_remove_place_data_source'),
    ]

    operations = [
    ]
