# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_auto_20161216_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='data_source',
            field=models.CharField(default='swissname3d', max_length=50, verbose_name='Where the place came from'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('data_source', 'source_id')]),
        ),
    ]
