# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0018_auto_20161216_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='data_source',
            field=models.CharField(default='homebytwo', max_length=50, verbose_name='Where the place came from'),
        ),
    ]
