# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:54
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ActivityType = apps.get_model("routes", "ActivityType")
    db_alias = schema_editor.connection.alias
    ActivityType.objects.using(db_alias).bulk_create([
        ActivityType(
            name="Run",
            default_vam_up="800",
            default_vam_down="4000",
            default_flat_pace="8000",
        ),
        ActivityType(
            name="Hike",
            default_vam_up="400",
            default_vam_down="2000",
            default_flat_pace="4000",
        ),
        ActivityType(
            name="Bike",
            default_vam_up="1200",
            default_vam_down="10000",
            default_flat_pace="20000",
        ),
        ActivityType(
            name="Ski",
            default_vam_up="400",
            default_vam_down="10000",
            default_flat_pace="4000",
        ),
    ])


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    ActivityType = apps.get_model("routes", "ActivityType")
    db_alias = schema_editor.connection.alias
    ActivityType.objects.using(db_alias).filter(name="Run").delete()
    ActivityType.objects.using(db_alias).filter(name="Hike").delete()
    ActivityType.objects.using(db_alias).filter(name="Bike").delete()
    ActivityType.objects.using(db_alias).filter(name="Ski").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20170321_1746'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
