# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20170328_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, verbose_name='Textual description'),
        ),
    ]
