# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20170328_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperformance',
            name='flat_speed',
        ),
        migrations.RemoveField(
            model_name='activityperformance',
            name='vam_down',
        ),
        migrations.RemoveField(
            model_name='activityperformance',
            name='vam_up',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='default_flat_speed',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='default_vam_down',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='default_vam_up',
        ),
        migrations.AddField(
            model_name='activityperformance',
            name='flat_param',
            field=models.FloatField(default=0.36),
        ),
        migrations.AddField(
            model_name='activityperformance',
            name='slope_param',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='activityperformance',
            name='slope_squared_param',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='activityperformance',
            name='total_elevation_gain_param',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='flat_param',
            field=models.FloatField(default=0.36),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='slope_param',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='slope_squared_param',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='total_elevation_gain_param',
            field=models.FloatField(default=0.1),
        ),
    ]
