---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }
    - { role: git }

    ## Database, choose either mysql or postgres, some subsequent roles will be configured
    ## depending on your choice here.
    # { role: mysql }
    - { role: postgresql }
    - { role: postgis }

    ## Install the ssh rule, installs gitlab.liip.ch and github.com host key
    - { role: ssh }

    ## Scripting / Language support
    # - { role: php-fpm }       # PHP using Nginx and PHP-FPM
    # - { role: php-apache }    # PHP using Apache and mod-php
    - { role: django }        # Django framework

    ## Install Compass in the box
    - { role: compass }

    ## Install Gulp with Drifter Gulpfile in the box
    - { role: gulp }

    ## Install Solr in the box
    # - { role: solr }

    ## Install Elasticsearch in the box
    # - { role: elasticsearch }

    ## Install some Gitlab CI scripts and .gitlab-ci.yml.
    ## See https://github.com/liip/drifter/blob/master/ci/README.md for details
    # - { role: gitlabci }

# Additional tasks
  tasks:
    - name: npm install sass and kanbasu
      shell: cd {{ root_directory }} && npm install

    - name: create ALLOWED_HOSTS file
      copy: "dest={{ django_root }}/envdir/ALLOWED_HOSTS content={{ hostname }} "
