- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    - { role: base }
    - { role: git }
    - { role: postgis }
    - { role: hd5 }
    - { role: django }
    - { role: rabbitmq }
    - { role: webpack }
    - { role: homebytwo_env }
    - { role: swissnames3d }

  tasks:
    - name: Ensure celery service exists
      copy:
        src: celery.service
        dest: /etc/systemd/system/celery.service
      become: yes

    - name: Reload systemd units
      command: systemctl daemon-reload
      become: yes

    - name: Install Celery systemd unit
      service:
        name: celery.service
        enabled: yes
        state: started
      become: yes
