---
- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    - { role: base }
    - { role: git }
    - { role: postgresql }
    - { role: postgis }
    - { role: django }

    ## Install Gulp with Drifter Gulpfile in the box
    - { role: gulp }

# Additional tasks
  tasks:
    - name: npm install sass and kanbasu
      shell: cd {{ root_directory }} && npm install
