# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravaroute',
            name='strava_route_id',
        ),
        migrations.RemoveField(
            model_name='stravaroute',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='stravaroute',
            name='type',
        ),
    ]
