# Generated by Django 2.2.16 on 2020-11-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0003_auto_20170315_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Swissname3dPlace',
        ),
    ]
