# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('importers', '0001_initial'), ('importers', '0002_swissname3dplace')]

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('routes', '0013_auto_20161214_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaRoute',
            fields=[
                ('route_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routes.Route')),
                ('strava_route_id', models.BigIntegerField(unique=True)),
                ('type', models.CharField(max_length=1)),
                ('sub_type', models.CharField(max_length=1)),
                ('strava_timestamp', models.IntegerField()),
            ],
            bases=('routes.route',),
        ),
        migrations.CreateModel(
            name='SwitzerlandMobilityRoute',
            fields=[
                ('route_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routes.Route')),
                ('switzerland_mobility_id', models.BigIntegerField(unique=True)),
                ('switzerland_mobility_owner', models.BigIntegerField(verbose_name='Wanderland user ID')),
                ('altitude', models.TextField(default='', verbose_name='Altitude information as JSON')),
            ],
            bases=('routes.route',),
        ),
        migrations.CreateModel(
            name='Swissname3dPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routes.Place')),
            ],
            bases=('routes.place',),
        ),
    ]
