# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_remove_place_data_source'),
        ('importers', '0001_squashed_0002_swissname3dplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swissname3dplace',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Swissname3dPlace',
        ),
        migrations.CreateModel(
            name='Swissname3dPlace',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('routes.place',),
        ),
    ]
