# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switzerlandmobilityroute',
            name='altitude',
            field=models.TextField(default='', verbose_name='Altitude information as JSON'),
        ),
        migrations.AddField(
            model_name='switzerlandmobilityroute',
            name='owner',
            field=models.BigIntegerField(default=0, verbose_name='Switzerland Mobility User ID'),
            preserve_default=False,
        ),
    ]
