# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20170125_1026'),
        ('importers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='route_ptr',
        ),
        migrations.DeleteModel(
            name='SwitzerlandMobilityRoute',
        ),
        migrations.CreateModel(
            name='SwitzerlandMobilityRoute',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('routes.route',),
        ),
    ]
