# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_auto_20161214_2306'),
        ('importers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swissname3dPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routes.Place')),
            ],
            bases=('routes.place',),
        ),
    ]
