# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0002_auto_20161216_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='switzerland_mobility_owner',
        ),
    ]
