# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importers', '0002_auto_20160629_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switzerlandmobilityroute',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
    ]
