# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20160630_1818'),
        ('importers', '0003_auto_20160630_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='created',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='id',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='length',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='totaldown',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='totalup',
        ),
        migrations.RemoveField(
            model_name='switzerlandmobilityroute',
            name='updated',
        ),
        migrations.AddField(
            model_name='switzerlandmobilityroute',
            name='route_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routes.Route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switzerlandmobilityroute',
            name='switzerland_mobility_owner',
            field=models.BigIntegerField(default=0, verbose_name='Wanderland user ID'),
            preserve_default=False,
        ),
    ]
